# Generated by Django 5.1 on 2024-09-17 13:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('genre', models.TextField()),
                ('rating', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='StoreEntry',
        ),
    ]
