# Generated by Django 5.1 on 2024-09-17 14:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_delete_storeentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='time',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
