# Generated by Django 5.1 on 2024-09-19 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_product_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='rating',
            new_name='review',
        ),
    ]
